'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")>  _
Partial Friend NotInheritable Class FFFGame
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As FFFGame = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New FFFGame()),FFFGame)
    
    Public Shared ReadOnly Property [Default]() As FFFGame
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property CorrectAnswerOptionsCount() As Short
        Get
            Return CType(Me("CorrectAnswerOptionsCount"),Short)
        End Get
        Set
            Me("CorrectAnswerOptionsCount") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("20")>  _
    Public Property GameDurationSeconds() As Double
        Get
            Return CType(Me("GameDurationSeconds"),Double)
        End Get
        Set
            Me("GameDurationSeconds") = value
        End Set
    End Property
End Class
